### ISSUE TITLE
Name broken when using system allocator

### ISSUE THREAD

**Issue by herrernst** [plietar/rust-dns-sd#3]
I got a weird bug where the registration name is broken.
I try this simple code:

```
            let svc = DNSService::register(Some("teststring"),
                                       "_spotify-connect._tcp",
                                       None,
                                       None,
                                       8000,
                                       &["VERSION=1.0", "CPath=/"]
                                       ).unwrap();
```

When compiling on Raspberry Pi 2 with the prebuilt ARMv7 Rust stable 1.7 compiler from https://github.com/warricksothr/RustBuild I get the exception `thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: DNSError(BadParam)', ../src/libcore/result.rs:688`. When runnning with gdb and breaking on the C function `DNSServiceRegister` I see the name mangled up:

```
Breakpoint 1, DNSServiceRegister (ret_sdref=0x7efff0ac, flags=0, interface=0, name=0x54acb600 "(\266\254T", 
    regtype=0x54acb610 "_spotify-connect._tcp", domain=0x0, host=0x0, port=16415, txtLen=20, txtRecord=0x54acb5e0, callback=0x0, 
    context=0x0) at compat.c:1095
1095    compat.c: No such file or directory.
(gdb) info args
ret_sdref = 0x7efff0ac
flags = 0
interface = 0
name = 0x54acb600 "(\266\254T"
regtype = 0x54acb610 "_spotify-connect._tcp"
domain = 0x0
host = 0x0
port = 16415
txtLen = 20
txtRecord = 0x54acb5e0
callback = 0x0
context = 0x0
```

Whereas, when running with an "older" nightly 1.8.0-dev (5c1d5fcd8 2016-01-22), I get the correct string:

```
Breakpoint 1, DNSServiceRegister (ret_sdref=0x7efff074, flags=0, interface=0, name=0x7642a030 "teststring", 
    regtype=0x7642c030 "_spotify-connect._tcp", domain=0x0, host=0x0, port=16415, txtLen=20, txtRecord=0x7642c018, callback=0x0, 
    context=0x0) at compat.c:1095
```

BTW, I don't really understand what mapping the Option<&str> to a Option<CString> does in https://github.com/plietar/rust-dns-sd/blob/master/src/lib.rs#L117 and then mapping it to a ptr in https://github.com/plietar/rust-dns-sd/blob/master/src/lib.rs#L126.

The bug seems to be triggered when using the system allocator, and not the default jemalloc one. The builds I use [disabled jemalloc around a month ago](https://github.com/warricksothr/RustBuild/commit/3e07bf3027ef73cc2c3eaf87f63fb90bd015f30e). That explains why I see the bug in the "new" stable build and not in the "old" nightly one. If I explicitly enable the system allocator:

```
#![feature(alloc_system)]
extern crate alloc_system;
```

I also get the bug on the older nightly and also on x64.

**Comment by plietar** [comment]
Thanks for the detailed report.
I wasn't able to reproduce it, but this should fix it.

**Comment by herrernst** [comment]
Thank you, works now!

**Comment by herrernst** [comment]
Maybe this was the reason for https://github.com/plietar/librespot/issues/49?
